### ISSUE TITLE
"> Saving model ..." The following error occurs during processing: What is the problem?

### ISSUE THREAD

**Issue by Kimyoungkoo** [nbarba/py3DRec#2]
Traceback (most recent call last):
  File "uncalibrated_rec.py", line 472, in <module>
    main(input_file=args.input_file,show=args.show)
  File "uncalibrated_rec.py", line 451, in main
    recModel.P=P
  File "D:\3DS\py3DRec-master\model.py", line 33, in P
    self._R, self._t = extract_rotation_translation(P)
NameError: name 'extract_rotation_translation' is not defined

**Comment by nbarba** [comment]
Hm, this function is a member of the main class. Did you get this error after downloading the code and running it?

**Comment by nbarba** [comment]
Does this issue still remain? I assume not (just did a fresh download and the code works), so I'll close the issue if I don't hear back.
