### ISSUE TITLE
SIFT algorithm for three images

### ISSUE THREAD

**Issue by Ashkansed** [nbarba/py3DRec#3]
Many thanks for your awesome  python code. I have an issue regarding extracting image features utilizing SIFT algorithm to create the "features.txt "file for the further processing in your code. I would be grateful if you might let mew know how can I create this file with SIFT algorithm for my own three images. I used matlab but it was not as optimized as your own features for the same pictures in your py3DRec Repository. 
Thank you in advance.

**Comment by nbarba** [comment]
The SIFT implementation I used was based on a C++ implementation of SIFT (which I cannot share due to license issues), but any SIFT implementation should give you similar feature points across your images. If I were you I would go with the OpenCV implementation, there is a great tutorial here: https://docs.opencv.org/3.4/da/df5/tutorial_py_sift_intro.html
Good luck!

**Comment by Ashkansed** [comment]
> The SIFT implementation I used was based on a C++ implementation of SIFT (which I cannot share due to license issues), but any SIFT implementation should give you similar feature points across your images. If I were you I would go with the OpenCV implementation, there is a great tutorial here: https://docs.opencv.org/3.4/da/df5/tutorial_py_sift_intro.html
> Good luck!

Thank you for your help. I have made my "Data.txt" file ready within the format you have described in your code. My problem is here that the number of each image features are different. Therefore, I have to make my data file with same feature numbers for each image. Is there any code to do this task automatically ( discarding some features to make the equal ones in all 3 images )? In this case, under discarding features we should also consider the robustness of the 3D model without losing or missing the data which is important for 3D rendering. 
In this file I have 2156 features for my first image, 1622 for the second one and 801 features for the third image.
Thank you in advance !

[data1.txt](https://github.com/nbarba/py3DRec/files/2971309/data1.txt)

**Comment by nbarba** [comment]
The code does not support having different number of features, but  the algorithm supports different number of features across views. The original implementation I had in the paper did that and worked pretty well. I had run experiments with different number of features across view pairs and worked pretty reliably as well. All you have to do is make sure you not use all the features when you update the 3D structure (which is what the current code does) and use the features present in both views.
